#include <stdio.h>
#include <stdlib.h>
/*

Author: Darcy Kenneth Olson

This code solves the following problem:

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

void generate_fibonacci(int n);
void initialize_fibonacci(int input[], int size);

int main()
{
    generate_fibonacci(32);
    return 0;
}


//This function fills an empty array with fibonacci numbers from 0 to size-1
void initialize_fibonacci(int input[], int size){
    input[0] = 1;
    input[1] = 2;
    int i;
    for(i = 2;i < size;i++){//This loop assigns address i the ith fibonacci number using the rule f_n = f_{n-1} + f_{n-2}
        input[i] = input[i-1] + input[i-2];
    }
}

//creates a list of fibonacci numbers, sums the even ones below 4 million, and prints the result
void generate_fibonacci(int n){
    int fibonacci_numbers [n];
    initialize_fibonacci(fibonacci_numbers,n);
    int index = 0, sum = 0;
    while(fibonacci_numbers[index] < 4000000){//This loop goes through the generated fibonacci numbers, checks if they're even and sums them if they are.
        if(fibonacci_numbers[index]%2 == 0){
            sum += fibonacci_numbers[index];
        }
        index++;
    }
    printf("The sum of even fibonaccis less than 4 million is %d \n",sum);
}
